name: Development
values:
  - key: baseUrl
    value: "http://localhost:8080"
    enabled: true
  - key: apiKey
    value: "vJDR15gscU/EoSxvCsmpvAPv5iHn3hPfnsKOkSNEvXw="
    enabled: true
  - key: accessToken
    value: ""
    enabled: true
