package com.clinicsystem.clinicapi.constant;

public class MessageCode {
    // General messages
    public static final String GENERAL_SUCCESS = "GENERAL_SUCCESS";
    public static final String GENERAL_ERROR = "GENERAL_ERROR";
    public static final String GENERAL_CREATED = "GENERAL_CREATED";
    public static final String GENERAL_UPDATED = "GENERAL_UPDATED";
    public static final String GENERAL_DELETED = "GENERAL_DELETED";

    // Error messages
    public static final String ERROR_VALIDATION = "ERROR_VALIDATION";
    public static final String ERROR_NOT_FOUND = "ERROR_NOT_FOUND";
    public static final String ERROR_BAD_REQUEST = "ERROR_BAD_REQUEST";
    public static final String ERROR_UNAUTHORIZED = "ERROR_UNAUTHORIZED";
    public static final String ERROR_FORBIDDEN = "ERROR_FORBIDDEN";
    public static final String ERROR_INTERNAL = "ERROR_INTERNAL";
    public static final String ERROR_BAD_CREDENTIALS = "ERROR_BAD_CREDENTIALS";

    // Authentication & Authorization
    public static final String AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
    public static final String AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
    public static final String AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
    public static final String AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID";
    public static final String AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED";
    public static final String AUTH_REFRESH_SUCCESS = "AUTH_REFRESH_SUCCESS";
    public static final String AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID";
    public static final String AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_TOKEN_EXPIRED";

    // API Key messages
    public static final String API_KEY_MISSING = "API_KEY_MISSING";
    public static final String API_KEY_INVALID = "API_KEY_INVALID";

    // User messages
    public static final String USER_NOT_FOUND = "USER_NOT_FOUND";
    public static final String USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
    public static final String USER_CREATED = "USER_CREATED";
    public static final String USER_UPDATED = "USER_UPDATED";
    public static final String USER_DELETED = "USER_DELETED";
    public static final String USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS";
    public static final String USER_PHONE_ALREADY_EXISTS = "USER_PHONE_ALREADY_EXISTS";
    public static final String USER_INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS";
    public static final String USER_ACCOUNT_INACTIVE = "USER_ACCOUNT_INACTIVE";

    // Password messages
    public static final String PASSWORD_CHANGED_SUCCESS = "PASSWORD_CHANGED_SUCCESS";
    public static final String PASSWORD_CURRENT_INCORRECT = "PASSWORD_CURRENT_INCORRECT";
    public static final String PASSWORD_MISMATCH = "PASSWORD_MISMATCH";
    public static final String PASSWORD_RESET_EMAIL_SENT = "PASSWORD_RESET_EMAIL_SENT";
    public static final String PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
    public static final String PASSWORD_RESET_TOKEN_INVALID = "PASSWORD_RESET_TOKEN_INVALID";
    public static final String PASSWORD_RESET_TOKEN_EXPIRED = "PASSWORD_RESET_TOKEN_EXPIRED";
    public static final String PASSWORD_RESET_TOKEN_USED = "PASSWORD_RESET_TOKEN_USED";

    // Validation messages - General
    public static final String VALIDATION_USERNAME_REQUIRED = "VALIDATION_USERNAME_REQUIRED";
    public static final String VALIDATION_USERNAME_SIZE = "VALIDATION_USERNAME_SIZE";
    public static final String VALIDATION_EMAIL_REQUIRED = "VALIDATION_EMAIL_REQUIRED";
    public static final String VALIDATION_EMAIL_INVALID = "VALIDATION_EMAIL_INVALID";
    public static final String VALIDATION_PASSWORD_REQUIRED = "VALIDATION_PASSWORD_REQUIRED";
    public static final String VALIDATION_PASSWORD_SIZE = "VALIDATION_PASSWORD_SIZE";
    public static final String VALIDATION_PASSWORD_MIN_SIZE = "VALIDATION_PASSWORD_MIN_SIZE";
    public static final String VALIDATION_CURRENT_PASSWORD_REQUIRED = "VALIDATION_CURRENT_PASSWORD_REQUIRED";
    public static final String VALIDATION_NEW_PASSWORD_REQUIRED = "VALIDATION_NEW_PASSWORD_REQUIRED";
    public static final String VALIDATION_CONFIRM_PASSWORD_REQUIRED = "VALIDATION_CONFIRM_PASSWORD_REQUIRED";
    public static final String VALIDATION_PASSWORD_MISMATCH = "VALIDATION_PASSWORD_MISMATCH";
    public static final String VALIDATION_PHONE_REQUIRED = "VALIDATION_PHONE_REQUIRED";
    public static final String VALIDATION_PHONE_INVALID = "VALIDATION_PHONE_INVALID";
    public static final String VALIDATION_PHONE_EXISTS = "VALIDATION_PHONE_EXISTS";
    public static final String VALIDATION_EMAIL_EXISTS = "VALIDATION_EMAIL_EXISTS";
    public static final String VALIDATION_FULLNAME_REQUIRED = "VALIDATION_FULLNAME_REQUIRED";
    public static final String VALIDATION_FULLNAME_SIZE = "VALIDATION_FULLNAME_SIZE";
    public static final String VALIDATION_DOB_REQUIRED = "VALIDATION_DOB_REQUIRED";
    public static final String VALIDATION_GENDER_INVALID = "VALIDATION_GENDER_INVALID";
    public static final String VALIDATION_TOKEN_REQUIRED = "VALIDATION_TOKEN_REQUIRED";
    public static final String VALIDATION_REFRESH_TOKEN_REQUIRED = "VALIDATION_REFRESH_TOKEN_REQUIRED";

    // Validation messages - Models
    public static final String VALIDATION_USER_REQUIRED = "VALIDATION_USER_REQUIRED";
    public static final String VALIDATION_PATIENT_REQUIRED = "VALIDATION_PATIENT_REQUIRED";
    public static final String VALIDATION_DOCTOR_REQUIRED = "VALIDATION_DOCTOR_REQUIRED";
    public static final String VALIDATION_APPOINTMENT_REQUIRED = "VALIDATION_APPOINTMENT_REQUIRED";
    public static final String VALIDATION_SPECIALTY_REQUIRED = "VALIDATION_SPECIALTY_REQUIRED";
    public static final String VALIDATION_SERVICE_REQUIRED = "VALIDATION_SERVICE_REQUIRED";
    public static final String VALIDATION_MEDICATION_REQUIRED = "VALIDATION_MEDICATION_REQUIRED";
    public static final String VALIDATION_PRESCRIPTION_REQUIRED = "VALIDATION_PRESCRIPTION_REQUIRED";
    public static final String VALIDATION_INVOICE_REQUIRED = "VALIDATION_INVOICE_REQUIRED";
    public static final String VALIDATION_EQUIPMENT_REQUIRED = "VALIDATION_EQUIPMENT_REQUIRED";
    public static final String VALIDATION_CONVERSATION_REQUIRED = "VALIDATION_CONVERSATION_REQUIRED";
    public static final String VALIDATION_PROMOTION_REQUIRED = "VALIDATION_PROMOTION_REQUIRED";
    public static final String VALIDATION_MEDICAL_RECORD_REQUIRED = "VALIDATION_MEDICAL_RECORD_REQUIRED";
    public static final String VALIDATION_QUEUE_NUMBER_REQUIRED = "VALIDATION_QUEUE_NUMBER_REQUIRED";

    // Validation messages - Fields
    public static final String VALIDATION_NAME_REQUIRED = "VALIDATION_NAME_REQUIRED";
    public static final String VALIDATION_CODE_REQUIRED = "VALIDATION_CODE_REQUIRED";
    public static final String VALIDATION_SLUG_REQUIRED = "VALIDATION_SLUG_REQUIRED";
    public static final String VALIDATION_PRICE_REQUIRED = "VALIDATION_PRICE_REQUIRED";
    public static final String VALIDATION_QUANTITY_REQUIRED = "VALIDATION_QUANTITY_REQUIRED";
    public static final String VALIDATION_RATING_REQUIRED = "VALIDATION_RATING_REQUIRED";
    public static final String VALIDATION_RATING_MIN = "VALIDATION_RATING_MIN";
    public static final String VALIDATION_RATING_MAX = "VALIDATION_RATING_MAX";
    public static final String VALIDATION_DATE_REQUIRED = "VALIDATION_DATE_REQUIRED";
    public static final String VALIDATION_TIME_REQUIRED = "VALIDATION_TIME_REQUIRED";
    public static final String VALIDATION_START_TIME_REQUIRED = "VALIDATION_START_TIME_REQUIRED";
    public static final String VALIDATION_END_TIME_REQUIRED = "VALIDATION_END_TIME_REQUIRED";
    public static final String VALIDATION_START_DATE_REQUIRED = "VALIDATION_START_DATE_REQUIRED";
    public static final String VALIDATION_END_DATE_REQUIRED = "VALIDATION_END_DATE_REQUIRED";
    public static final String VALIDATION_AMOUNT_REQUIRED = "VALIDATION_AMOUNT_REQUIRED";
    public static final String VALIDATION_TITLE_REQUIRED = "VALIDATION_TITLE_REQUIRED";
    public static final String VALIDATION_MESSAGE_REQUIRED = "VALIDATION_MESSAGE_REQUIRED";
    public static final String VALIDATION_TYPE_REQUIRED = "VALIDATION_TYPE_REQUIRED";
    public static final String VALIDATION_STATUS_REQUIRED = "VALIDATION_STATUS_REQUIRED";
    public static final String VALIDATION_DIAGNOSIS_REQUIRED = "VALIDATION_DIAGNOSIS_REQUIRED";
    public static final String VALIDATION_QUESTION_REQUIRED = "VALIDATION_QUESTION_REQUIRED";
    public static final String VALIDATION_ANSWER_REQUIRED = "VALIDATION_ANSWER_REQUIRED";
    public static final String VALIDATION_DESCRIPTION_REQUIRED = "VALIDATION_DESCRIPTION_REQUIRED";
    public static final String VALIDATION_SENDER_REQUIRED = "VALIDATION_SENDER_REQUIRED";
    public static final String VALIDATION_AUTHOR_REQUIRED = "VALIDATION_AUTHOR_REQUIRED";
    public static final String VALIDATION_ACTIVITY_TYPE_REQUIRED = "VALIDATION_ACTIVITY_TYPE_REQUIRED";
    public static final String VALIDATION_SETTING_KEY_REQUIRED = "VALIDATION_SETTING_KEY_REQUIRED";
    public static final String VALIDATION_ACTION_REQUIRED = "VALIDATION_ACTION_REQUIRED";
    public static final String VALIDATION_CONTENT_REQUIRED = "VALIDATION_CONTENT_REQUIRED";

    // Validation messages - Specific codes
    public static final String VALIDATION_APPOINTMENT_CODE_REQUIRED = "VALIDATION_APPOINTMENT_CODE_REQUIRED";
    public static final String VALIDATION_PATIENT_CODE_REQUIRED = "VALIDATION_PATIENT_CODE_REQUIRED";
    public static final String VALIDATION_DOCTOR_CODE_REQUIRED = "VALIDATION_DOCTOR_CODE_REQUIRED";
    public static final String VALIDATION_STAFF_CODE_REQUIRED = "VALIDATION_STAFF_CODE_REQUIRED";
    public static final String VALIDATION_RECORD_CODE_REQUIRED = "VALIDATION_RECORD_CODE_REQUIRED";
    public static final String VALIDATION_PRESCRIPTION_CODE_REQUIRED = "VALIDATION_PRESCRIPTION_CODE_REQUIRED";
    public static final String VALIDATION_INVOICE_CODE_REQUIRED = "VALIDATION_INVOICE_CODE_REQUIRED";
    public static final String VALIDATION_PAYMENT_CODE_REQUIRED = "VALIDATION_PAYMENT_CODE_REQUIRED";
    public static final String VALIDATION_EQUIPMENT_CODE_REQUIRED = "VALIDATION_EQUIPMENT_CODE_REQUIRED";
    public static final String VALIDATION_PROMOTION_CODE_REQUIRED = "VALIDATION_PROMOTION_CODE_REQUIRED";

    // Validation messages - Dates
    public static final String VALIDATION_APPOINTMENT_DATE_REQUIRED = "VALIDATION_APPOINTMENT_DATE_REQUIRED";
    public static final String VALIDATION_MONTH_REQUIRED = "VALIDATION_MONTH_REQUIRED";
    public static final String VALIDATION_MONTH_RANGE = "VALIDATION_MONTH_RANGE";
    public static final String VALIDATION_YEAR_REQUIRED = "VALIDATION_YEAR_REQUIRED";
    public static final String VALIDATION_REPORT_DATE_REQUIRED = "VALIDATION_REPORT_DATE_REQUIRED";
    public static final String VALIDATION_LEAVE_DATE_REQUIRED = "VALIDATION_LEAVE_DATE_REQUIRED";
    public static final String VALIDATION_PRESCRIPTION_DATE_REQUIRED = "VALIDATION_PRESCRIPTION_DATE_REQUIRED";
    public static final String VALIDATION_INVOICE_DATE_REQUIRED = "VALIDATION_INVOICE_DATE_REQUIRED";
    public static final String VALIDATION_DAY_OF_WEEK_REQUIRED = "VALIDATION_DAY_OF_WEEK_REQUIRED";

    // Validation messages - Amounts/Numbers
    public static final String VALIDATION_SUBTOTAL_REQUIRED = "VALIDATION_SUBTOTAL_REQUIRED";
    public static final String VALIDATION_TOTAL_AMOUNT_REQUIRED = "VALIDATION_TOTAL_AMOUNT_REQUIRED";
    public static final String VALIDATION_TOTAL_PRICE_REQUIRED = "VALIDATION_TOTAL_PRICE_REQUIRED";
    public static final String VALIDATION_UNIT_PRICE_REQUIRED = "VALIDATION_UNIT_PRICE_REQUIRED";
    public static final String VALIDATION_DISCOUNT_VALUE_REQUIRED = "VALIDATION_DISCOUNT_VALUE_REQUIRED";
    public static final String VALIDATION_DISCOUNT_AMOUNT_REQUIRED = "VALIDATION_DISCOUNT_AMOUNT_REQUIRED";
    public static final String VALIDATION_DISCOUNT_TYPE_REQUIRED = "VALIDATION_DISCOUNT_TYPE_REQUIRED";
    public static final String VALIDATION_POINTS_REQUIRED = "VALIDATION_POINTS_REQUIRED";
    public static final String VALIDATION_BALANCE_AFTER_REQUIRED = "VALIDATION_BALANCE_AFTER_REQUIRED";

    // Validation messages - Other
    public static final String VALIDATION_ITEM_TYPE_REQUIRED = "VALIDATION_ITEM_TYPE_REQUIRED";
    public static final String VALIDATION_ITEM_NAME_REQUIRED = "VALIDATION_ITEM_NAME_REQUIRED";
    public static final String VALIDATION_PAYMENT_METHOD_REQUIRED = "VALIDATION_PAYMENT_METHOD_REQUIRED";
    public static final String VALIDATION_TRANSACTION_TYPE_REQUIRED = "VALIDATION_TRANSACTION_TYPE_REQUIRED";
    public static final String VALIDATION_MAINTENANCE_TYPE_REQUIRED = "VALIDATION_MAINTENANCE_TYPE_REQUIRED";
    public static final String VALIDATION_REPORT_TYPE_REQUIRED = "VALIDATION_REPORT_TYPE_REQUIRED";

    // Resource messages
    public static final String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";

    // Patient messages
    public static final String PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND";
    public static final String PATIENT_ALREADY_EXISTS = "PATIENT_ALREADY_EXISTS";
    public static final String PATIENT_CREATED = "PATIENT_CREATED";
    public static final String PATIENT_UPDATED = "PATIENT_UPDATED";
    public static final String PATIENT_DELETED = "PATIENT_DELETED";

    // Doctor messages
    public static final String DOCTOR_NOT_FOUND = "DOCTOR_NOT_FOUND";
    public static final String DOCTOR_CREATED = "DOCTOR_CREATED";
    public static final String DOCTOR_UPDATED = "DOCTOR_UPDATED";
    public static final String DOCTOR_DELETED = "DOCTOR_DELETED";

    // Service messages
    public static final String SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND";
    public static final String SERVICE_CREATED = "SERVICE_CREATED";
    public static final String SERVICE_UPDATED = "SERVICE_UPDATED";
    public static final String SERVICE_DELETED = "SERVICE_DELETED";

    // Specialty messages
    public static final String SPECIALTY_NOT_FOUND = "SPECIALTY_NOT_FOUND";
    public static final String SPECIALTY_CREATED = "SPECIALTY_CREATED";
    public static final String SPECIALTY_UPDATED = "SPECIALTY_UPDATED";
    public static final String SPECIALTY_DELETED = "SPECIALTY_DELETED";

    // System messages
    public static final String SYSTEM_ERROR = "SYSTEM_ERROR";

    public static final String FAQ_NOT_FOUND = "FAQ_NOT_FOUND";

    private MessageCode() {
        // Private constructor to prevent instantiation
    }
}
